import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    bg: {
        width: '100%',
        height: '60%',
    },
    bg2: {
        width: '100%',
        height: '35%',
    },
    title: {
        backgroundColor: 'transparent',
        marginLeft: 0,
        marginRight: 'auto',
        marginTop: 30,
        fontSize: 30,
        fontFamily: 'RobotoSlab_Regular',
        fontWeight: '700',
        color: 'black',
    },
    inputsBox: {
        alignSelf: 'center',
        marginTop: 10,
        width: '100%',
        backgroundColor: '#FFFFFF',
        position: 'relative',
    },
    inputs: {
        height: 60,
        width: '100%',
        margin: 0,
        fontSize: 18,
        paddingHorizontal: 15,
        color: '#00000080',
        borderBottomColor: 'black',
        borderBottomWidth: 2,
    },
    submitButton: {
        width: '100%',
        height: 41,
        borderRadius: 7,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        backgroundColor: 'black',
        marginTop: 25,
    },
    linkToSignup: {
        fontSize: 16,
        textTransform: 'uppercase',
        color: '#A0A0A0',
        textDecorationLine: 'underline',
    },
    buttonToSignup: {
        marginTop: '10%',
        marginLeft: '60%',
    },
    boxTitleAuthorization: {
        fontSize: 20,
        maxWidth: 160,
        position: 'absolute',
        bottom: '-30%',
        paddingLeft: 39,
        paddingRight: 39,
        paddingTop: 15,
        paddingBottom: 15,
        backgroundColor: 'white',
        borderBottomRightRadius: 50,
        borderTopRightRadius: 50,
        shadowColor: '#000',
        shadowOffset: {
            width: 2,
            height: 7,
        },
        shadowOpacity: 0.09,
        shadowRadius: 5,
        elevation: 7,
    },
    titleAuthorization: {
        textTransform: 'uppercase',
        fontSize: 20,
        fontFamily: 'RobotoSlab_Bold',
        fontWeight: '800',
        color: '#2A4D60',
    },
    arrowBack: {
        position: 'absolute',
        top: 50,
        left: 25,
    },
});
